services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dma_system
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgres

  flask-api:
    build:
      context: ./document_processor
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  postgres:
    driver: bridge
