import * as dotenv from 'dotenv';
dotenv.config();

export const {
  PORT,
  DB_PORT,
  DB_HOST,
  DB_PASS,
  DB_USER,
  DB_NAME,
  DB_DIALECT,
  DB_CERT,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_REGION,
  AWS_S3_BUCKET_NAME,
  AWS_S3_PATH,
  AWS_S3_SIGNED_URL_EXPIRATION,
} = process.env;
